### ISSUE TITLE
Tiles from https://nwy-tiles-api.prod.newaydata.com/ blank

### ISSUE THREAD

**Issue by tim-wyatt** [AmbitiousPilots/LittleNavmapOFMTheme#23]
Is the API for downloading tiles still working? I'm getting black in the areas I would expect to see a map (e.g. Frankfurt). If I use the URL directly I get a file, just blank.

Going to the  newaydata.com website there's no reference to the API, so maybe they've removed it for commercial reasons?

**Comment by jonaseberle** [comment]
Using the changes from https://github.com/AmbitiousPilots/LittleNavmapOFMTheme/pull/20/files (that change is imperative for the project - it uses "latest" instead of the non-available AIRAC 2205) it works still fine for me.

Example tile from around EDDF:
https://nwy-tiles-api.prod.newaydata.com/tiles/12/2140/1387.jpg?path=latest/base/latest
https://nwy-tiles-api.prod.newaydata.com/tiles/12/2140/1387.png?path=latest/aero/latest

**Comment by tim-wyatt** [comment]
Worked. Thanks. Are you merging that to main?

**Comment by albar965** [comment]
Original author seems inactive as far as I can see. Last commit was April 2022. 
Maybe it's better to fork it.
Alex

**Comment by tim-wyatt** [comment]
Yeah that's not a bad idea
